application: php1-1223
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1
  
- url: /(.+\.html)$
  script: \1
  
- url: /PHP/mrwheely/stylesheets
  static_dir: PHP/mrwheely/stylesheets
  
- url: /PHP/monkeybusiness/stylesheets
  static_dir: PHP/monkeybusiness/stylesheets
  
- url: /.*
  script: index.php